Development
habibullah791/Training-Labs pull request #2
Opened 2023-09-18 00:35 UTC by habibullah791

ADD .gitignore, testcase and CHANGE the file structure

2023-09-18 00:45 UTC, mohdanss requested changes
Update .gitignore to ignore all the files, like __pycache__ etc.

2023-09-18 01:19 UTC, mohdanss requested changes

2023-09-18 01:19 UTC, mohdanss commented on DC-322-L-1 Web Engineering Lab/main.py
> +def registerAccount():
Make sure to follow consistency, python supoorts single and double quotes for string. But adhere to use any of it as a sign of clean and consistent code. 

- Either use '' or "", all across your code.
- Use @ as a sign of readability in docstring
- mention parameters & return type in your functions. (as in example below!)
- You mostly mentioned return in docstring as none or None, be consistent, and follow what's suppoorted in python, its 'None'.

A sample docstring can be like this:
def sum(a: int, b: int) -> int:
    ''' 
        @param a: first number
        @param b: second number

        @desc: sum of two numbers

        @return: sum of a and b
    '''
    return a + b

def printSum(a: int, b: int) -> None:
    ''' 
        @param a: first number
        @param b: second number    

        @description: print sum of two numbers
        @return: None
    '''
    print(sum(a, b))

2023-09-18 01:19 UTC, mohdanss commented on DC-322-L-1 Web Engineering Lab/main.py
> +    utils.registerHeader()
There should be a level of abstraction.
Use 
from utils import * 
from utils import -some specific function/class etc.

Just call it by name. No need to mention utils. everywhere.

2023-09-18 01:19 UTC, mohdanss commented on DC-322-L-1 Web Engineering Lab/main.py
> +        Returns:
wouldn't it be better if:
returns:
    atmData: array user dictionaries, that has updated data after the amouunt has been deposited.

2023-09-18 01:19 UTC, mohdanss commented on DC-322-L-1 Web Engineering Lab/main.py
> +            account["account_balance"] = str(
avoid such indentations, which create confusion, keep it at the same line. CHANGE REST OF SUCH INCONSISTENCIES TOO.

2023-09-18 01:19 UTC, mohdanss commented on DC-322-L-1 Web Engineering Lab/utils.py
> +    with open('atmData.txt', 'r') as file:
wrap this in try/catch block, what if file doesn't exists?

2023-09-18 01:19 UTC, mohdanss commented on DC-322-L-1 Web Engineering Lab/utils.py
> +    accountData = [str(item) for item in accountDetails]
Whenever using such statements, which are not clear to beginner, add some comments. - Always write a code, which could be understood by a child wiith the help of comments.

2023-09-18 01:20 UTC, closed without merging

2023-09-18 01:27 UTC, mohdanss commented
On each CRUD - file is being updated, I deposit something, it updates the file, I withdraw, it does same. Try something, which can save us from this trouble of costly approach.

HINT: You'll need to read a file at start of the program, and write while existing the system.

2023-09-19 22:25 UTC, habibullah791 commented
Sure I've updated the project